### ISSUE TITLE
URI exception trying to pull Cookbook.all or cookbook info

### ISSUE THREAD

**Issue by wdeviers** [sethvargo/chef-api#31]
Howdy;
When I try:
irb(main):093:0> cbs = Cookbook.all
URI::InvalidURIError: bad URI(is not URI?): {"url"=>"https://chef.hostname/organizations/homeslice/cookbooks/airbrake_handler", "versions"=>[{"version"=>"1.1.1", "url"=>"https://chef.hostname/organizations/homeslice/cookbooks/airbrake_handler/1.1.1"}]}
        from /usr/lib/ruby/1.9.1/uri/common.rb:176:in `split'
        from /usr/lib/ruby/1.9.1/uri/common.rb:211:in `parse'
        from /usr/lib/ruby/1.9.1/uri/common.rb:747:in `parse'
        from /var/lib/gems/1.9.1/gems/chef-api-0.5.0/lib/chef-api/connection.rb:320:in `build_uri'
        from /var/lib/gems/1.9.1/gems/chef-api-0.5.0/lib/chef-api/connection.rb:193:in `request'
        from /var/lib/gems/1.9.1/gems/chef-api-0.5.0/lib/chef-api/connection.rb:106:in `get'
        from /var/lib/gems/1.9.1/gems/chef-api-0.5.0/lib/chef-api/resources/base.rb:366:in `block in each'
        from /var/lib/gems/1.9.1/gems/chef-api-0.5.0/lib/chef-api/resources/base.rb:365:in `each'
        from /var/lib/gems/1.9.1/gems/chef-api-0.5.0/lib/chef-api/resources/base.rb:365:in `each'
        from /var/lib/gems/1.9.1/gems/chef-api-0.5.0/lib/chef-api/resources/base.rb:392:in `entries'
        from /var/lib/gems/1.9.1/gems/chef-api-0.5.0/lib/chef-api/resources/base.rb:392:in `all'
        from (irb):93
        from /usr/bin/irb:12:in `<main>'

Cookbook.list works correct; .fetch pulls a Cookbook object but cb.versions.first also throws URI errors with all versions listed inside a hash table with "url", and some..recursive arrays?. It looks like the Cookbook or CookbookVersion class is passing a hash to the URI handler:

irb(main):104:0> cb.versions.first
URI::InvalidURIError: bad URI(is not URI?): {"url"=>"https://chef.server.com/organizations/homeslice/cookbooks/windows", "versions"=>[{"version"=>"1.36.1", "url"=>"https://chef.server.com/organizations/homeslice/cookbooks/windows/1.36.1"}, {"version"=>"1.34.8", "url"=>"https://chef.server.com/organizations/homeslice/cookbooks/windows/1.34.8"}, {"version"=>"1.34.6", "url"=>"https://chef.server.com/organizations/homeslice/cookbooks/windows/1.34.6"}, {"version"=>"1.34.2", "url"=>"https://chef.server.com/organizations/homeslice/cookbooks/windows/1.34.2"}, {"version"=>"1.34.0", "url"=>"https://chef.server.com/organizations/homeslice/cookbooks/windows/1.34.0"}, {"version"=>"1.33.1", "url"=>"https://chef.server.com/organizations/homeslice/cookbooks/windows/1.33.1"}, {"version"=>"1.32.0", "url"=>"https://chef.server.com/organizations/homeslice/cookbooks/windows/1.32.0"}, {"version"=>"1.31.0", "url"=>"https://chef.server.com/organizations/homeslice/cookbooks/windows/1.31.0"}, {"version"=>"1.11.0", "url"=>"https://chef.server.com/organizations/homeslice/cookbooks/windows/1.11.0"}]}

I'll try to dig in deeper on this when I get back to work, but I'm new at Ruby... we'll see.  Any thoughts would be appreciated.

**Comment by sethvargo** [comment]
There's an open PR to finish cookbooks. They use a totally different API structure
