### ISSUE TITLE
Is this the correct way to pull from a databag. 

### ISSUE THREAD

**Issue by spuder** [sethvargo/chef-api#38]
The documentation on databags could use some more examples. I'm happy to provide them, but I have the following questions before I open a merge request. 

Do you need a double fetch to get a databag item? 

    foo.data_bags.fetch('aDatabag').items.fetch('aDataBagID').data['aDataBagItem']

This is the only way I can get databags to work. It has the strange side effect that this one databag item establishes 4 server connections. Is there no more efficient way? 

```ruby
2.2.0 :114 > foo.data_bags.fetch('nd-web').items.fetch('deploy-version').data['deploy-version-ecm2']
W: Disabling SSL verification...
W: Neither ChefAPI nor the maintainers are responsible for damanges incurred as a result of disabling SSL verification. Please use this with extreme caution, or consider specifying a custom certificate using `config.ssl_pem_file'.
W: Disabling SSL verification...
W: Neither ChefAPI nor the maintainers are responsible for damanges incurred as a result of disabling SSL verification. Please use this with extreme caution, or consider specifying a custom certificate using `config.ssl_pem_file'.
W: Disabling SSL verification...
W: Neither ChefAPI nor the maintainers are responsible for damanges incurred as a result of disabling SSL verification. Please use this with extreme caution, or consider specifying a custom certificate using `config.ssl_pem_file'.
W: Disabling SSL verification...
W: Neither ChefAPI nor the maintainers are responsible for damanges incurred as a result of disabling SSL verification. Please use this with extreme caution, or consider specifying a custom certificate using `config.ssl_pem_file'.
 => "20150708.1"
```

Also, is the 'data_bag_item' not implemented? It doesn't appear to be something that you can call directly. (I don't know ruby well enough to understand what is going on with it)

```ruby
2.2.0 :116 > foo.data_bag_item
NoMethodError: undefined method `data_bag_item' for #<ChefAPI::Connection:0x007fc670ab8bd0>
	from (irb):116
	from /Users/sowen/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
2.2.0 :117 > foo.data_bag_items
NoMethodError: undefined method `data_bag_items' for #<ChefAPI::Connection:0x007fc670ab8bd0>
	from (irb):117
	from /Users/sowen/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
```

**Comment by spuder** [comment]
I've been testing this further, and I still the only way I'm able to successfully pull from a databag is with two fetches. 

Is this the intended use case? 

    foo.data_bags.fetch('aDatabag').items.fetch('aDataBagID').data['aDataBagItem']

**Comment by spuder** [comment]
@sethvargo Any comment on this?

**Comment by sethvargo** [comment]
@spuder nope, sorry. It takes a lot to context switch into Chef and a lot has changed since I originally started writing this. I'll dig in more when I get a chance, but it's not a high priority item for me at this time :smile:
