### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by geewiz** [sethvargo/chef-api#41]
Hi Seth,

do you have any plans to release the changes/fixes of the recent months? Is there something we can help with?

Best regards,  
  Jochen

**Comment by sethvargo** [comment]
Hi @geewiz 

I do not have a release planned at this time.

Best,
Seth

**Comment by geewiz** [comment]
Hi @sethvargo, sorry to bother you again!

Some more background to my question: We're trying to import hundreds of data bag items from our Chef server and the import failed somewhere in between with a 401 error. This looked like issue #39.

Today, I managed to verify my assumption by cutting my own gem version from master. The import finished successfully.

Now I'm unsure how to get a current gem into our production application on Heroku. What would you recommend?

Best regards,  
  Jochen
